server:
  port: 8080
  servlet:
    context-path: /shop 
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/productdb"
    username: root
    password: DuHoangHuy@abc1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
